language: node_js
node_js:
  - '4'
  - '6'
  - '8'
sudo: false
before_install:
  - npm install -g grunt-cli
env:
  - MONGODB_VERSION=2.4
  - MONGODB_VERSION=3.2
services:
  - mongodb
before_script:
  - mongo admin --eval 'db.createUser({user:"admin",pwd:"admin",roles:[{role:"userAdminAnyDatabase",db:"admin"}]});'
script:
  - grunt
  - grunt coverallsio
